name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please check existing issues and discussions first.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve?
      placeholder: I'm trying to do X but there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: Add a new API like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What workarounds or alternatives have you considered?
      placeholder: I could use X but it's not ideal because...

  - type: checkboxes
    id: checklist
    attributes:
      label: Additional context
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
